#!/bin/bash
#
# Copyright 2015 the original author or authors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

##############################################################################
#
#   Gradle start up script for POSIX generated by Gradle.
#
#   Important for running:
#
#   (1) You need a POSIX-compliant shell to run this script. If your /bin/sh does
#       not find so, but you have some other compatible shell available, most
#       probably you want to use that instead.
#
#   (2) Upstream is slowly deprecating POSIX shell, so this script is generated
#       with use of `sed` from the original Gradle bash script; if you suspect an
#       issue relating bash/sed, report this to Gradle and not to your Linux
#       distribution.
#
##############################################################################

# Attempt to set APP_HOME
# Resolve links: $0 may be a link
app_path=$0

# Need this for daisy-chained symlinks.
while
    APP_HOME=${app_path%"${app_path##*/}"}    # leaves a trailing slash where not needed
    # Append a slash if the path does not end in a slash for consistency.
    [[ "$APP_HOME" != */ ]] && APP_HOME="$APP_HOME"/
    app_path=$(readlink -f "$app_path")
    [[ $app_path != "$APP_HOME"* ]] && break
do
    continue
done

# This is normally unused
# shellcheck disable=SC2034
APP_NAME="Gradle"
APP_HOME="$(cd "${APP_HOME%/*}" && pwd -P)"/gradle/wrapper
# Add default JVM options here. You can also use JAVA_OPTS and GRADLE_OPTS to pass JVM options to this script.
DEFAULT_JVM_OPTS='"-Xmx64m" "-Xms64m"'

# Use the maximum available, or set MAX_FD != -1 to use that value.
MAX_FD=maximum

warn () {
    echo "$*"
} >&2

die () {
    echo
    echo "$*"
    echo
    exit 1
} >&2

# OS specific support (must be 'true' or 'false').
cygwin=false
msys=false
darwin=false
nonstop=false
case "$( uname )" in                #(
  CYGWIN* )         cygwin=true  ;; #(
  Darwin* )         darwin=true  ;; #(
  MSYS* | MINGW* )  msys=true    ;; #(
  NONSTOP* )        nonstop=true ;;
esac

# Determine the Java command to use to start the JVM.
if [[ -n "$JAVA_HOME" ]] && [[ -f "$JAVA_HOME/bin/java" ]]; then
    javaexe="$JAVA_HOME/bin/java"
elif type -p java >/dev/null 2>&1; then
    javaexe=$(type -p java)
else
    javaexe=
fi

if [[ -z "$javaexe" ]]; then
    if $darwin; then
        echo "Error: JAVA_HOME is not set and no 'java' command could be found in your PATH." >&2
    else
        echo "Error: JAVA_HOME is not set and no 'java' command could be found in your PATH." >&2
        echo
        echo "Please set the JAVA_HOME variable in your environment to match the" >&2
        echo "location of your Java installation." >&2
    fi
    exit 1
fi

# Increase the maximum file descriptors if we can.
if ! "$cygwin" && ! "$msys" ; then
    case $- in #(
      *i*) ;; #( interactive shell; assume user knows what they do
      *)   set -o nounset ;; #(
    esac
    ulimit -n "$MAX_FD" ||
        warn "Could not set maximum file descriptor limit to $MAX_FD"
fi

# Escape application args
for arg do
    if [[ $arg =~ ^-?.* ]]; then   # an option string
        printf '%s\n' "$arg"
    else
        printf '%q\n' "$arg"       # probably a filename
    fi
done | sed -e 's/^/-/' | tr '\n' ' ' | sed -e 's/^ *//;s/ *$//'
}

# Collect all arguments for the java command;
#   * $DEFAULT_JVM_OPTS, $JAVA_OPTS, and $GRADLE_OPTS can contain fragments of
#     shell script including quotes and variable substitutions, so put them in
#     double quotes to make sure that they get re-expanded; and
#   * put everything else in single quotes, so that it's not re-expanded.

set -- \
        "-Dorg.gradle.appname=$APP_BASE_NAME" \
        -classpath "$CLASSPATH" \
        org.gradle.wrapper.GradleWrapperMain \
        "$@"

# Stop when "xargs" has seen a form feed, newline, '\0' or an argument that is 1024+ bytes
if (
    noarg=--no-argument
    # ... but if it ends with " $noarg", truncate $noarg
    tr '\0' '\n' | sed 's/ $//g' | tr -s ' ' '\n' |
    head -n -1 |
    grep -v '\\$' |
    tr -s '\n' ' '
) | grep -q .
then
    eval "set -- $(\
        printf '%s\n' "$DEFAULT_JVM_OPTS $JAVA_OPTS $GRADLE_OPTS" |
        xargs -n1 |
        sed 's/^-//' |
        sed 's/=/-/' |
        tr '\n' ' '
    ) \"\$@\""
fi

exec "$javaexe" "$@"
